# tfsec configuration
severity_overrides:
  google-gke-enable-stackdriver-logging: WARNING
  google-gke-enable-stackdriver-monitoring: WARNING
  google-gke-use-cluster-labels: LOW

exclude:
  - google-gke-enable-private-cluster  # Private cluster not required for this setup
  - google-gke-node-pool-uses-cos      # Using default node image

minimum_severity: MEDIUM
