# Example: Deploy to on-demand nodes (critical workloads)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-critical
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-critical
  template:
    metadata:
      labels:
        app: myapp-critical
    spec:
      tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "on-demand"
        effect: "NoSchedule"
      nodeSelector:
        workload-type: on-demand
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/hyperbola-476507/docker-repo/app:latest
