# Example: Deploy to spot nodes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-spot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      nodeSelector:
        workload-type: spot
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/hyperbola-476507/docker-repo/app:latest
