---
# API Key Secret for Session Manager Authentication
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: default
type: Opaque
stringData:
  # IMPORTANT: Change this to a strong random key in production!
  # Generate with: openssl rand -base64 32
  api-key: "your-secure-api-key-change-in-production"
