apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: default
  labels:
    app: backup-storage
spec:
  accessModes:
    - ReadWriteOnce  # Single node access (backup jobs run sequentially)
  resources:
    requests:
      storage: 50Gi  # Shared backup storage
  storageClassName: standard-rwo
