apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: default
  labels:
    app: backup-storage
spec:
  accessModes:
    - ReadWriteMany  # Multiple pods can write backups
  resources:
    requests:
      storage: 50Gi  # Shared backup storage
  storageClassName: standard-rwo
