---
# Create fresh namespace
apiVersion: v1
kind: Namespace
metadata:
  name: fresh-system
---
# Redis
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: fresh-system
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: fresh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: fresh-system
type: Opaque
stringData:
  password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: fresh-system
type: Opaque
stringData:
  api-key: "your-secure-api-key-change-in-production"
---
# Backup PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: fresh-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard-rwo
---
# Backup Storage Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-storage
  namespace: fresh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-storage
  template:
    metadata:
      labels:
        app: backup-storage
    spec:
      containers:
      - name: backup-storage
        image: busybox:latest
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: backup-volume
          mountPath: /backup
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: backup-volume
        persistentVolumeClaim:
          claimName: backup-pvc
---
# Session Manager RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: session-manager
  namespace: fresh-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: session-manager
  namespace: fresh-system
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "delete", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: ["keda.sh"]
  resources: ["scaledobjects", "triggerauthentications"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: session-manager
  namespace: fresh-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: session-manager
subjects:
- kind: ServiceAccount
  name: session-manager
  namespace: fresh-system
---
# Session Manager
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-manager
  namespace: fresh-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session-manager
  template:
    metadata:
      labels:
        app: session-manager
    spec:
      serviceAccountName: session-manager
      containers:
      - name: session-manager
        image: us-central1-docker.pkg.dev/hyperbola-476507/docker-repo/session-manager:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: password
        - name: SESSION_TTL
          value: "86400"
        - name: USER_POD_IMAGE
          value: "us-central1-docker.pkg.dev/hyperbola-476507/docker-repo/ai-environment:latest"
        - name: USER_POD_PORT
          value: "8080"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-credentials
              key: api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: session-manager
  namespace: fresh-system
spec:
  type: LoadBalancer
  selector:
    app: session-manager
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
---
# Cross-namespace RBAC - Allow fresh-system session-manager to create resources in default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fresh-session-manager-default
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "delete", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: ["keda.sh"]
  resources: ["scaledobjects", "triggerauthentications"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fresh-session-manager-default
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fresh-session-manager-default
subjects:
- kind: ServiceAccount
  name: session-manager
  namespace: fresh-system
---
# Redis TriggerAuthentication for KEDA
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: redis-trigger-auth
  namespace: default
spec:
  secretTargetRef:
  - parameter: password
    name: fresh-redis-credentials
    key: password
---
# Volume Snapshot Class for GKE persistent disk snapshots
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-gce-pd-snapshot-class
driver: pd.csi.storage.gke.io
deletionPolicy: Retain
---
# Volume Snapshot RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: volumesnapshot-creator
  namespace: fresh-system
rules:
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: session-manager-snapshot
  namespace: fresh-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: volumesnapshot-creator
subjects:
- kind: ServiceAccount
  name: session-manager
  namespace: fresh-system