---
# Redis TriggerAuthentication for KEDA (needed for fresh-system)
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: redis-trigger-auth
  namespace: default
spec:
  secretTargetRef:
  - parameter: password
    name: fresh-redis-credentials
    key: password
