apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: myapp
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-critical-pdb
  namespace: prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: myapp-critical
