apiVersion: v1
kind: ServiceAccount
metadata:
  name: session-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: session-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: ["keda.sh"]
  resources: ["scaledobjects"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: session-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: session-manager
subjects:
- kind: ServiceAccount
  name: session-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-manager
  template:
    metadata:
      labels:
        app: session-manager
    spec:
      serviceAccountName: session-manager
      containers:
      - name: session-manager
        image: us-central1-docker.pkg.dev/hyperbola-476507/docker-repo/session-manager:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: session-manager
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: session-manager
