apiVersion: v1
kind: ConfigMap
metadata:
  name: test-api
data:
  app.py: |
    from flask import Flask, request
    import redis
    
    app = Flask(__name__)
    r = redis.Redis(host='redis', port=6379, decode_responses=True)
    
    @app.route('/')
    def home():
        return '''
        <h1>Pod Sleep/Wake Test</h1>
        <button onclick="wake()">Wake Pod</button>
        <button onclick="sleep()">Sleep Pod (clear queue)</button>
        <button onclick="status()">Check Status</button>
        <pre id="output"></pre>
        <script>
        function wake() {
            fetch('/wake').then(r => r.json()).then(d => {
                document.getElementById('output').innerText = JSON.stringify(d, null, 2);
            });
        }
        function sleep() {
            fetch('/sleep').then(r => r.json()).then(d => {
                document.getElementById('output').innerText = JSON.stringify(d, null, 2);
            });
        }
        function status() {
            fetch('/status').then(r => r.json()).then(d => {
                document.getElementById('output').innerText = JSON.stringify(d, null, 2);
            });
        }
        </script>
        '''
    
    @app.route('/wake')
    def wake():
        r.lpush('user_messages', 'test:wake')
        return {'action': 'wake', 'queue_length': r.llen('user_messages')}
    
    @app.route('/sleep')
    def sleep_pod():
        r.delete('user_messages')
        return {'action': 'sleep', 'queue_length': r.llen('user_messages')}
    
    @app.route('/status')
    def status():
        return {'queue_length': r.llen('user_messages')}
    
    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=5000)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
      - name: test-api
        image: python:3.11-slim
        command: ["/bin/sh", "-c"]
        args:
          - pip install flask redis && python /app/app.py
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: app
          mountPath: /app
      volumes:
      - name: app
        configMap:
          name: test-api
---
apiVersion: v1
kind: Service
metadata:
  name: test-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: test-api
