name: Deploy to GKE

on:
  push:
    branches: [main]
    paths:
      - 'k8s-manifests/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: false
        type: choice
        options:
          - dev
          - prod
        default: 'dev'
      image_tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
  workflow_call:
    inputs:
      image_tag:
        required: false
        type: string
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Load Config
        id: config
        run: |
          echo "project_id=$(grep 'project_id' terraform.tfvars | cut -d'=' -f2 | tr -d ' "')" >> $GITHUB_OUTPUT
          echo "region=$(grep 'region' terraform.tfvars | cut -d'=' -f2 | tr -d ' "')" >> $GITHUB_OUTPUT
          echo "cluster_name=$(grep 'cluster_name' terraform.tfvars | cut -d'=' -f2 | tr -d ' "')" >> $GITHUB_OUTPUT
          echo "repository_id=$(grep 'repository_id' terraform.tfvars | cut -d'=' -f2 | tr -d ' "')" >> $GITHUB_OUTPUT

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ steps.config.outputs.cluster_name }}
          location: ${{ steps.config.outputs.region }}

      - name: Validate manifests
        run: |
          kubectl apply --dry-run=client -f k8s-manifests/ || true

      - name: Create Namespaces
        run: |
          kubectl apply -f k8s-manifests/namespace-*.yaml

      - name: Deploy Priority Classes
        run: |
          kubectl apply -f k8s-manifests/priority-classes.yaml || true

      - name: Deploy Security & Network Policies
        run: |
          kubectl apply -f k8s-manifests/security/ || true
          kubectl apply -f k8s-manifests/network-policies/ || true

      - name: Deploy Pod Disruption Budgets
        run: |
          kubectl apply -f k8s-manifests/pod-disruption-budget.yaml || true

      - name: Deploy Services
        run: |
          kubectl apply -f k8s-manifests/service.yaml || true

      - name: Deploy HPA
        run: |
          kubectl apply -f k8s-manifests/hpa.yaml || true

      - name: Set Image Tag
        id: set_tag
        run: |
          IMAGE_TAG="${{ inputs.image_tag || 'latest' }}"
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "Using image tag: ${IMAGE_TAG}"

      - name: Deploy Applications
        run: |
          IMAGE="${{ steps.config.outputs.region }}-docker.pkg.dev/${{ steps.config.outputs.project_id }}/${{ steps.config.outputs.repository_id }}/app:${{ steps.set_tag.outputs.image_tag }}"
          
          # Update deployment manifests with correct image
          sed -i "s|image:.*|image: ${IMAGE}|g" k8s-manifests/deployment.yaml
          sed -i "s|image:.*|image: ${IMAGE}|g" k8s-manifests/deployment-critical.yaml
          
          kubectl apply -f k8s-manifests/deployment.yaml
          kubectl apply -f k8s-manifests/deployment-critical.yaml

      - name: Wait for Rollout
        id: rollout
        run: |
          echo "Waiting for default namespace deployment..."
          kubectl rollout status deployment/app --timeout=5m || echo "Default deployment rollout failed"
          
          echo "Waiting for prod namespace deployment..."
          kubectl rollout status deployment/app-critical -n prod --timeout=5m || echo "Prod deployment rollout failed"
        continue-on-error: true

      - name: Rollback on Failure
        if: steps.rollout.outcome == 'failure'
        run: |
          echo "❌ Deployment failed, rolling back..."
          kubectl rollout undo deployment/app || true
          kubectl rollout undo deployment/app-critical -n prod || true
          exit 1

      - name: Deploy Monitoring & Ingress
        if: steps.rollout.outcome == 'success'
        run: |
          kubectl apply -f k8s-manifests/monitoring/ || true
          kubectl apply -f k8s-manifests/ingress/ || true

      - name: Verify Deployment
        if: always()
        run: |
          echo "### Deployment Status" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          echo "=== Pods Status ===" | tee -a $GITHUB_STEP_SUMMARY
          kubectl get pods -l app=myapp -o wide || true
          kubectl get pods -n prod -l app=myapp-critical -o wide || true
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "=== Services ===" | tee -a $GITHUB_STEP_SUMMARY
          kubectl get svc app-service || true
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "=== HPA Status ===" | tee -a $GITHUB_STEP_SUMMARY
          kubectl get hpa || true
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "=== PDB Status ===" | tee -a $GITHUB_STEP_SUMMARY
          kubectl get pdb --all-namespaces || true

      - name: Run Health Checks
        if: steps.rollout.outcome == 'success'
        run: |
          echo "Running health checks..."
          for pod in $(kubectl get pods -l app=myapp -o name 2>/dev/null); do
            kubectl exec $pod -- wget -q -O- http://localhost:8080/health 2>/dev/null || echo "⚠️  Health check failed for $pod"
          done
        continue-on-error: true
