name: Deploy to GKE

on:
  push:
    branches: [main]
    paths:
      - 'k8s-manifests/**'
      - '.github/workflows/k8s-deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - prod
      image_tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ vars.GKE_CLUSTER_NAME }}
          location: ${{ vars.GCP_REGION }}

      - name: Validate manifests
        run: |
          kubectl apply --dry-run=client -f k8s-manifests/

      - name: Create Namespaces
        run: |
          kubectl apply -f k8s-manifests/namespace-*.yaml

      - name: Deploy Security & Network Policies
        run: |
          kubectl apply -f k8s-manifests/security/
          kubectl apply -f k8s-manifests/network-policies/

      - name: Deploy Core Resources
        run: |
          find k8s-manifests/ -name '*.yaml' ! -name 'namespace-*.yaml' ! -path '*/security/*' ! -path '*/network-policies/*' ! -path '*/ingress/*' ! -path '*/monitoring/*' -exec kubectl apply -f {} \;

      - name: Update Image
        id: update_image
        run: |
          kubectl set image deployment/app app=${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPO_ID }}/app:${{ inputs.image_tag }} || true
          kubectl set image deployment/app-critical -n prod app=${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPO_ID }}/app:${{ inputs.image_tag }} || true

      - name: Wait for Rollout
        id: rollout
        run: |
          kubectl rollout status deployment/app --timeout=5m
          kubectl rollout status deployment/app-critical -n prod --timeout=5m
        continue-on-error: true

      - name: Rollback on Failure
        if: steps.rollout.outcome == 'failure'
        run: |
          echo "Deployment failed, rolling back..."
          kubectl rollout undo deployment/app
          kubectl rollout undo deployment/app-critical -n prod
          exit 1

      - name: Deploy Monitoring & Ingress
        if: steps.rollout.outcome == 'success'
        run: |
          kubectl apply -f k8s-manifests/monitoring/ || true
          kubectl apply -f k8s-manifests/ingress/ || true

      - name: Verify deployment
        run: |
          echo "=== Pods Status ==="
          kubectl get pods -l app=myapp -o wide
          kubectl get pods -n prod -l app=myapp-critical -o wide
          
          echo "=== Services ==="
          kubectl get svc app-service
          
          echo "=== HPA Status ==="
          kubectl get hpa
          
          echo "=== PDB Status ==="
          kubectl get pdb --all-namespaces
          
          echo "=== Network Policies ==="
          kubectl get networkpolicies --all-namespaces

      - name: Run Health Checks
        run: |
          for pod in $(kubectl get pods -l app=myapp -o name); do
            kubectl exec $pod -- wget -q -O- http://localhost:8080/health || echo "Health check failed for $pod"
          done
