name: Terraform Drift Detection

on:
  schedule:
    - cron: '0 8 * * 1-5'  # Weekdays at 8 AM UTC
  workflow_dispatch:

jobs:
  detect-drift:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -detailed-exitcode -no-color > plan_output.txt 2>&1
          EXIT_CODE=$?
          echo "exitcode=${EXIT_CODE}" >> $GITHUB_OUTPUT
          cat plan_output.txt
          exit 0
        continue-on-error: true

      - name: Check for Drift
        if: steps.plan.outputs.exitcode == '2'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('plan_output.txt', 'utf8');
            const truncatedPlan = plan.length > 10000 ? plan.substring(0, 10000) + '\n\n... (truncated)' : plan;
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ Terraform Drift Detected',
              body: `## Terraform Drift Detected
              
Infrastructure drift has been detected in your GCP environment.

### What this means:
- Manual changes were made in GCP Console
- Resources were modified outside of Terraform
- Infrastructure state doesn't match code

### Plan Output:
\`\`\`terraform
${truncatedPlan}
\`\`\`

### Next Steps:
1. Review the changes above
2. Run \`terraform plan\` locally to see full details
3. Either:
   - Import manual changes into Terraform
   - Run \`terraform apply\` to revert to desired state

**Detected at:** ${new Date().toISOString()}`,
              labels: ['infrastructure', 'drift', 'automated']
            });

      - name: No Drift Detected
        if: steps.plan.outputs.exitcode == '0'
        run: echo "✅ No drift detected. Infrastructure matches Terraform state."
