name: Terraform Check

on:
  pull_request:
    branches: [main]
    paths:
      - '**.tf'
      - 'modules/**/*.tf'
      - '.github/workflows/terraform-*.yml'
      - '!k8s-manifests/**'
      - '!k8s-examples/**'
  push:
    branches: [main]
    paths:
      - '**.tf'
      - 'modules/**/*.tf'
      - '.github/workflows/terraform-*.yml'
      - '!k8s-manifests/**'
      - '!k8s-examples/**'

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: TFLint Init
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: TFLint
        run: tflint --recursive
