name: Unlock Terraform State (Emergency)

on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: 'Lock ID to remove (from error message)'
        required: true
      confirm:
        description: 'Type "UNLOCK" to confirm'
        required: true

jobs:
  unlock:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'UNLOCK'
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Force Unlock
        run: |
          echo "⚠️  EMERGENCY UNLOCK - Use only if workflow is stuck!"
          echo "Lock ID: ${{ github.event.inputs.lock_id }}"
          terraform force-unlock -force ${{ github.event.inputs.lock_id }}
          echo "✅ Lock removed"

      - name: Verify
        run: |
          echo "### State Unlocked" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Lock ID \`${{ github.event.inputs.lock_id }}\` has been removed." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "⚠️  **Next Steps:**" >> $GITHUB_STEP_SUMMARY
          echo "1. Verify no one else is running terraform" >> $GITHUB_STEP_SUMMARY
          echo "2. Re-run your terraform workflow" >> $GITHUB_STEP_SUMMARY
